### ISSUE TITLE
The properties in schema.yaml should have a field called title.

### ISSUE THREAD

**Issue by wgrzelak** [GoogleCloudPlatform/marketplace-k8s-app-tools#169]
The properties in schema.yaml should have a field called `title` that can be used to set a custom title in the Cloud Launcher instead of using the property name.

Example:
```
RABBITMQ_DEFAULT_USER:
  title: RabbitMQ username
  type: string
  default: rabbit
```
