### ISSUE TITLE
GENERATED_PASSWORD does not work in "Helm" implementation

### ISSUE THREAD

**Issue by gmflau** [GoogleCloudPlatform/marketplace-k8s-app-tools#203]
We tried to use GENERATED_PASSWORD in our schema.yaml for our Helm implementation as follows but failed:

schema.yaml:
```
  ....
  opscAdminPassword:
    type: string
    x-google-marketplace:
      type: GENERATED_PASSWORD
      generatedPassword:
        length: 16
   ....
```
secret.yaml:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "dse.fullname" . }}-opsc-admin-pwd-secret
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}"
    app.kubernetes.io/component: dse
    app: {{ template "dse.fullname" . }}-opsc
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: dse
type: Opaque
data:
  password: "$opscAdminPassword"
```

When running "make app/install", we got the following error in our deployer job's pod:
Error from server (BadRequest): error when creating "/data/resources.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret: ObjectMeta: v1.ObjectMeta: TypeMeta: Kind: Data: decode base64: illegal base64 data at input byte 0, error found in #10 byte of ...|nPassword"},"kind":"|..., bigger context ...|sion":"v1","data":{"password":"$opscAdminPassword"},"kind":"Secret","metadata":{"annotations":{"kube|...

Are we missing something?
