### ISSUE TITLE
[testrunner] Support execTest

### ISSUE THREAD

**Issue by huyhg** [GoogleCloudPlatform/marketplace-k8s-app-tools#267]
To replace the current `bashTest`.

```yaml
- name: Some test
  execTest:
    # This uses the default container of the testrunner, whose entrypoint is bash.
    args:
    - -c
    - 'redis ping'
 
- name: Some test
  execTest:
    container: redis
    args:
    # Still using the default entrypoint of the container.
    # In this case, the default entrypoint is already `redis`.
    - ping
 
- name: Some test
  execTest:
    container: redis
    command:
    # This replaces the entrypoint of the container, fully specifies the command.
    # Note that the first item must be a valid binary. This is why we cannot
    # pass multiple commands in this form.
    - redis
    - ping
 
- name: Some test
  execTest:
    container: dev
    # Script form. Implementation: (1) create an executable file with this content,
    # and (2) execute that file directly (as the entrypoint).
    # This way, shebang lines will be honored, and we can run python or anything
    # else here.
    script: |-
      #!/bin/bash -eu
      apt-get update && apt-get install mysql
 
- name: Some test
  execTest:
    # You can rebake the container here.
    dockerfile: |-
      FROM python
      RUN pip install custom-library
    script: |-
      #!/bin/python2
      ...
```
