### ISSUE TITLE
Cannot provide integer env variable to tests

### ISSUE THREAD

**Issue by wgrzelak** [GoogleCloudPlatform/marketplace-k8s-app-tools#308]
This is my `tester.yaml.template` file:

```
...
  - name: tester
    image: "${testerImage}"
    imagePullPolicy: Always
    env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APP_INSTANCE_NAME
      value: ${APP_INSTANCE_NAME}
    - name: REPLICAS
      value: 3
  restartPolicy: Never
```

And this is the error message:

```
spec:
  containers:
  - env:
    - name: NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: APP_INSTANCE_NAME
      value: apptest-m24ixj70
    - name: REPLICAS
      value: 3
    image: gcr.io/orbitera-dev/nginx/test
    imagePullPolicy: Always
    name: tester
  restartPolicy: Never
  serviceAccountName: apptest-m24ixj70-deployer-sa
+ run_tester.py --namespace apptest-m24ixj70 --manifest /data/tester.yaml --timeout 300

      kubectl apply
      --namespace="apptest-m24ixj70"
      --filename="/data/tester.yaml"
      
Traceback (most recent call last):
  File "/bin/run_tester.py", line 103, in <module>
    main()
  File "/bin/run_tester.py", line 42, in main
    print_call=True)
  File "/bin/bash_util.py", line 39, in __init__
    self._run()
  File "/bin/bash_util.py", line 66, in _run
    raise CommandException(self._error)
bash_util.CommandException: Error from server (BadRequest): error when creating "/data/tester.yaml": Pod in version "v1" cannot be handled as a Pod: v1.Pod.Spec: v1.PodSpec.ServiceAccountName: RestartPolicy: Containers: []v1.Container: v1.Container.Name: ImagePullPolicy: Image: Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found 3, error found in #10 byte of ...|,"value":3}],"image"|..., bigger context ...|":"apptest-m24ixj70"},{"name":"REPLICAS","value":3}],"image":"gcr.io/gcp-project/nginx/test","image|...

INFO Deleting namespace "apptest-m24ixj70"
```
