### ISSUE TITLE
Allow setting values for helm chart arrays

### ISSUE THREAD

**Issue by calind** [GoogleCloudPlatform/marketplace-k8s-app-tools#353]
I'm trying to create a solution using the helm deployer. The chart I'm using requires me to set the `extraArgs[]` array in order to inject the image the controller uses. This is currently not possible.

__`schema.yaml`__

```yaml
cert-manager.extraArgs[1]:
  type: string
  default: $REGISTRY/cert-manager-acmesolver:$TAG
  x-google-marketplace:
    type: IMAGE
```

__`values.yaml`__
```yaml
cert-manager:
  extraArgs:
    - ----acme-http01-solver-image
    - quay.io/jetstack/cert-manager-acmesolver:v0.6.2
```

Is there any workaround or alternative solution to this?
