### ISSUE TITLE
maxLength field is ignored for NAME type

### ISSUE THREAD

**Issue by ovk6** [GoogleCloudPlatform/marketplace-k8s-app-tools#398]
When specified in schema.yaml maxLength field in name property it is ignored and some default value is used.

Is it possible to specify maximum length for application name? It is needed because of software limitation for some fields length, eg. cluster name, which is derived from app name.

Example schema.yaml content:

```yaml
properties:
  name:
    type: string
    maxLength: 26
    x-google-marketplace:
      type: NAME
```

Output not as expected:
![Screenshot from 2019-08-27 16-14-48](https://user-images.githubusercontent.com/17149009/63778813-d352dd80-c8e5-11e9-8185-cdf9c660659e.png)
