### ISSUE TITLE
Dealing with upgrades after adding StorageClass reference in schema.yaml

### ISSUE THREAD

**Issue by vkamra** [GoogleCloudPlatform/marketplace-k8s-app-tools#440]
We'd like to modify our application to be deployed with a SSD StorageClass instead of using the default StorageClass in the cluster. As described in the docs, we will add a ref in schema.yaml [1].

We're unsure how to deal with upgrades in this case for application instances that are already deployed and have PVCs created with the default storage class. Kubernetes will not allow modifying the storageclass field for a bound PVC.

[1]
```
properties:
  ssdStorageClass:
    type: string
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
```
