### ISSUE TITLE
Using base64 encoded strings fails creating the secret

### ISSUE THREAD

**Issue by AMecea** [GoogleCloudPlatform/marketplace-k8s-app-tools#484]
tools version: 0.10.1

In the `scheme.yaml`
```
  dashboardOIDCClientID:
    type: string
    title: Auth0 Client ID
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dashboardOIDCClientIDEncoded
```

in the `apptest/deployer/schema.yaml`     
```                                                                                                                                        
properties:
  dashboardOIDCClientID:
    type: string
    title: Auth0 Client ID
    default: "test"
    x-google-marketplace:
      type: STRING
      string:
        generatedProperties:
          base64Encoded: dashboardOIDCClientIDEncoded
```

running `mpdev verify`
I'm getting:
```
Error from server (BadRequest): error when creating "/data/resources.yaml": Secret in version "v1" cannot be handled as a Secret: v1.Secret.Data: decode base64: illegal base64 data at input byte 1, error found in #10 byte of ...|dGVzdA=='","CLIENT_S|..., bigger context ...|apiVersion":"v1","data":{"CLIENT_ID":"b'dGVzdA=='","CLIENT_SECRET":"b'dGVzdA=='","ISSUER":"b'aHR0cHM|...
```

This is because the variable is replaced with `b'<base64 encoded string>'` instead of just the string, this is related to python3 byte string that is not decoded before serialization.
