### ISSUE TITLE
Add CONFIG_FILE type to x-google-marketplace property 

### ISSUE THREAD

**Issue by pgoldtho** [GoogleCloudPlatform/marketplace-k8s-app-tools#485]
As a marketplace application developer I would like the ability to accept configuration file input from the Marketplace UI so that I can accept configuration parameters that cannot be expressed as key-value pairs.

One way to do this would be to extend the x-google-marketplace property to included a CONFIG_FILE type.  It would be used to generate a data entry field in the Cloud Marketplace UI where a user could upload a local file or specify a cloud storage resource location.

The uploaded file contents would replace a file with default/placeholder values in a helm chart directory which would be accessed using Files.Get as shown below

```
chart
└── my-application
    ├── Chart.yaml
    ├── config.js
    ├── logo.png
    ├── templates
    │   ├── application.yaml
    │   ├── manifest.yaml
    └── values.yaml
```

```
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-conf-js
type: Opaque
stringData:
  database.js: |-
{{ .Files.Get "config.js" | indent 4 }}
```
