### ISSUE TITLE
The test runner "bashTest" does not show stderr and stdout on failure

### ISSUE THREAD

**Issue by maelvls** [GoogleCloudPlatform/marketplace-k8s-app-tools#565]
We are using the official [`gcr.io/cloud-marketplace-tools/testrunner`](https://github.com/GoogleCloudPlatform/marketplace-testrunner) image to run our [smoke tests](https://github.com/jetstack/jetstack-secure-gcm/blob/main/smoke-test.yaml).

Unfortunately, the `bashTest` mode makes it very hard to debug bash-based tests: stdout and stderr are not displayed.

For example with this test image:

```Dockerfile
FROM gcr.io/cloud-marketplace-tools/testrunner:0.1.2
WORKDIR /
COPY test.yaml /test.yaml
ENTRYPOINT ["testrunner", "-logtostderr", "--test_spec=/test.yaml"]
```

And with `test.yaml` as follows:

```yaml
# test.yaml
actions:
  - name: Some test
    bashTest:
      script: foo
      expect:
        exitCode:
          equals: 0
```

`mpdev` only shows status code, not stdout nor stderr:

```sh
>>> Running /test.yaml
PASSED
>   0: Some test
FAILED: Bash test failed > Unexpected exit status code > Should have equaled 0, but was 127
>> Summary: 2 FAILED, 5 PASSED
```

I would expect `testrunner` to show stderr and stdout, e.g.:

```sh
>>> Running /test.yaml
PASSED
>   0: Some test
>   bash: command not found: foo
FAILED: Bash test failed > Unexpected exit status code > Should have equaled 0, but was 127
>> Summary: 1 FAILED, 0 PASSED
```

Right now, our workaround is to add a "sleep" step that allows us to reproduce the error and find out what caused it:

```yaml
actions:
  - name: Hang for debugging purposes
    bashTest:
      script: sleep 1200 # 20 minutes
```

My questions:
1. Do you have a plan to improve the developer experience with the `bashTest`?
2. Can we build our own test image without relying on `testrunner`? I.e., is running the `testrunner` image mandatory to get approved on the Marketplace?

cc @huyhg
