### ISSUE TITLE
The application uid should no be displayed in the Marketplace UI

### ISSUE THREAD

**Issue by calind** [GoogleCloudPlatform/marketplace-k8s-app-tools#585]
Given the following `schema.yaml`:

```yaml
x-google-marketplace:
  schemaVersion: v2
properties:
  name:
    type: string
    x-google-marketplace:
      type: NAME
  namespace:
    type: string
    x-google-marketplace:
      type: NAMESPACE
  bitpoke.application.uid:
    type: string
    x-google-marketplace:
      type: APPLICATION_UID
```

It displays a the application uid field in the Marketplace UI:
<img width="543" alt="Screenshot 2022-02-08 at 11 20 02" src="https://user-images.githubusercontent.com/266375/152956324-07bc13ac-50c2-4ad1-a616-ae223c75c5e7.png">

Is there a way to hide that field? My expectation was that the application uid is not something user-editable, but rather a value generated by the deployer.
