### ISSUE TITLE
How to use RWX storage class in schema.yaml

### ISSUE THREAD

**Issue by clementchane** [GoogleCloudPlatform/marketplace-k8s-app-tools#615]
Hello,

I m trying to create a container app for GCP marketplace and it depends on ReadWriteMany PVCs.
When using the local mpdev tool to use the default storage class "standard-rwx" it works fine using the default addon for CSI file : GcpFilestoreCsiDriver

However for marketplace, I understand that I need to declare this storage class in the schema.yaml file, as I get the error "standard-rwx" storage class not found when I submit it in the producer portal.

The only part I found on this is https://github.com/GoogleCloudPlatform/marketplace-k8s-app-tools/blob/master/docs/schema.md : 
```
properties:
  ssdStorageClass:
    type: string
    x-google-marketplace:
      type: STORAGE_CLASS
      storageClass:
        type: SSD
```
However it creates a provisioner type gce-pd which is ReadWriteOnce only it seems.
The doc doesnt list any other option.

How can I make that work? Is there any option for the storageclass to accept RWX? Or is it possible to run the marketplace automated tests in a cluster with the Filestore CSI driver addon?

Thanks for your help!
