### ISSUE TITLE
Minor feature request - kubernetes specific datatypes for schema.yml

### ISSUE THREAD

**Issue by moxious** [GoogleCloudPlatform/marketplace-k8s-app-tools#90]
In the way you provide these:

```
  reportingSecret:
    type: string
    x-google-marketplace:
      type: REPORTING_SECRET  
```

There are certain special datatypes which presumably the UI will enforce, this should be a base64 encoded SA key, I guess.

So too other kubernetes primitives would be really useful as data types.  For example:
* Volume sizes/disk allocations
* CPU resource requests

E.g. I want to provide variables like this:

```
  cpu:
    title: CPU units per node
    type: string
    default: "1"
  mem:
    title: Memory per node
    type: string
    default: "2Gi"
  volumeSize:
    title: Disk allocation to core nodes
    type: string
    default: "10Gi"
  volumeStorageClass:
    title: Storage class for nodes, pd-ssd for SSD storage recommended.
    type: string
    default: "pd-ssd"
    enum:
    - pd-ssd
    - pd-standard
```

I'm imagining something like standardized regexes or specialized datatypes so that I can ensure the user doesn't request `-3m` CPUs, or `fishGi` of memory.
